### ISSUE TITLE
Start Lita Deamon without lida -d

### ISSUE THREAD

**Issue by anduonghien** [litaio/lita#190]
Hell everybody. When I start `deamon lita` with command `lita -d`, I got message

```Lita's built-in daemonization is deprecated without replacement and will be removed in Lita 5.0. Use your operating system's process manager instead.```

It work ok because my version is not 5.0, but I have 1 question.

I don't know `Use your operating system's process manager instead.`. So can you let me know how to start lita deamon via `operating system's process `?

Thank you.

**Comment by jimmycuadra** [comment]
Deployment is a big topic because there are many ways it can be done. The "system process manager" is something like init, systemd, upstart, or runit, and will vary based on what operating system the server you're deploying to is running and what software you have installed.

The [deployment guide](https://docs.lita.io/getting-started/deployment/) in Lita's user guide has a pretty thorough example of deploying to a CoreOS host using Docker and systemd.

It's also very easy to deploy Lita to Heroku, but it may cost money depending on your usage.

Another example is shown in [How To Install the Lita Chat Bot for IRC on Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-install-the-lita-chat-bot-for-irc-on-ubuntu-14-04), using Ubuntu and Upstart. (Note that in the most recent version of Ubuntu, Upstart has been replaced with systemd.)

Because there is no one right way to do it, deployment is really beyond the scope of what Lita can (and should) do itself, or thorough documentation. Hopefully the links I provided can get you started on the right track. If you have more questions, folks in our [IRC channel](https://webchat.freenode.net/?channels=lita.io) will probably be able to help.
